#!/usr/bin/python2
import jsonrpc
from jsonrpc import ServiceProxy
from os.path import expanduser
import socket
conf = {p[0]: p[1].strip() for p in 
    (l.split("=", 1) for l in open(expanduser("~/.bitcoin/bitcoin.conf")))
    if len(p) == 2}

proxy = ServiceProxy("http://%(rpcuser)s:%(rpcpassword)s@127.0.0.1:8332"%conf)
try:
    info = proxy.getinfo()
    print " ${color}balance:${color white}${alignr} %s BTC" % str(info["balance"])
    print " ${color}connections:${color white}${alignr} %s" % str(info["connections"])
    print " ${color}blocks:${color white}${alignr} %s" % str(info["blocks"])
except socket.error:
    print " ${color}Bitcoind is not running..."
