#!/usr/bin/python
import subprocess
try:
    moc_output = subprocess.check_output(["mocp", "--info"], stderr=subprocess.PIPE)
except:
    print(" ${color}Not Playing...")
    exit()
moc_output = moc_output.decode("UTF-8").splitlines()
info = dict(line.strip().split(": ", maxsplit=1) for line in moc_output)
if info["State"] in ("PLAY"):
    print(" ${color}title:${color white}",info["SongTitle"])
    print(" ${color}album:${color white}",info["Album"])
    print(" ${color}artist:${color white}",info["Artist"])
    print(" ${color}time:${color white}",info["CurrentTime"], "/", info["TotalTime"])
else:
    print(" ${color}Not Playing...")

